In [1]:
import numpy as np
import pandas as pd

In [84]:
class Perceptron(object):
    
    def __init__(self,noOfInputs,threshold=5,learningRate=1):
        self.threshold = threshold
        self.learningRate = learningRate
        self.weights = np.zeros(noOfInputs + 1)
        
    def predict(self,inputs):
        summation = np.dot(inputs,self.weights[1:]) + self.weights[0]
        if summation>0:
            activation = 1
        else:
            activation = 0
        return activation
    
    def train(self,trainingInputs,labels):
        for _ in range(self.threshold):
            for inputs , label in zip(trainingInputs,labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learningRate * (label - prediction) * inputs 
                self.weights[0:] += self.learningRate * (label - prediction)
                print(self.weights)

In [85]:
trainingInputs = []
trainingInputs.append(np.array([1,1]))
trainingInputs.append(np.array([1,0]))
trainingInputs.append(np.array([0,1]))
trainingInputs.append(np.array([0,0]))
 
labels = np.array([1,0,0,0])

perceptron = Perceptron(2)
perceptron.train(trainingInputs,labels)

[1. 2. 2.]
[0. 0. 1.]
[-1. -1. -1.]
[-1. -1. -1.]
[0. 1. 1.]
[-1. -1.  0.]
[-1. -1.  0.]
[-1. -1.  0.]
[0. 1. 2.]
[-1. -1.  1.]
[-1. -1.  1.]
[-1. -1.  1.]
[0. 1. 3.]
[-1. -1.  2.]
[-2. -2.  0.]
[-2. -2.  0.]
[-1.  0.  2.]
[-1.  0.  2.]
[-2. -1.  0.]
[-2. -1.  0.]


In [86]:
inputs = np.array([0,0])
print(perceptron.predict(inputs))

0


In [117]:
movieData = pd.read_csv("./Datasets/Movie_DATA.csv",names=["name","Action","Thriller","Comedy","Like/Dislike"]) #random dataset genrated online
features = ["Action","Thriller","Comedy"]
main_input = movieData.loc[:,features].values
output = movieData.loc[:,['Like/Dislike']].values
main_input =main_input[1:50]
trainingInputs = []
for temp in main_input:
    temp_arry = []
    for temp_values in temp:
        if( temp_values== "true"):
             temp_arry.append(1)
        else:
            temp_arry.append(0)
    trainingInputs.append(np.array(temp_arry))
    
labels =[]
for temp_values in output:
    if( temp_values== "true"):
        labels.append(1)
    else:
        labels.append(0)
    
labels = np.array(labels)


perceptron = Perceptron(3)
perceptron.train(trainingInputs,labels)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[1. 2. 2. 1.]
[ 0.  1.  0. -1.]
[ 0.  1.  0. -1.]
[-1. -1. -2. -2.]
[ 0.  1.  0. -1.]
[ 0.  1.  0. -1.]
[ 0.  1.  0. -1.]
[1. 3. 1. 1.]
[1. 3. 1. 1.]
[ 0.  2. -1.  0.]
[ 0.  2. -1.  0.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[1. 3. 0. 1.]
[ 0.  1. -1. -1.]
[ 0.  1. -1. -1.]
[1. 3. 1. 0.]
[1. 3. 1. 0.]
[1. 3. 1. 0.]
[ 0.  2. -1. -2.]
[ 1.  3.  1. -1.]
[ 1.  3.  1. -1.]
[ 1.  3.  1. -1.]
[ 0.  1.  0. -3.]
[ 0.  1.  0. -3.]
[ 1.  2.  1. -1.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[ 1.  2.  2. -1.]
[ 0.  1.  0. -3.]
[ 0.  1.  0. -3.]
[ 0.  1.  0. -3.]
[-1. -1. -2. -4.]
[ 0.  1. -1. -3.]
[ 0.  1. -1. -3.]
[ 1.  3.  1. -1.]
[ 1.  3.  1. -1.]
[ 1.  3.  1. -1.]
[ 1.  3.  1. -1.]
[ 0.  1.  0. -2.]
[ 1.  2.  1. -1.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[-1. -1. -2. -3.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[ 0.  1.  0. -2.]
[1. 3. 1. 0.]
[1. 3.

<h5>Lineraly Not seprable
</h5>

In [118]:
inputs = np.array([1,0,0]) 
print(perceptron.predict(inputs))

1
