In [4]:
import numpy as np

In [17]:
class Perceptron(object):
    
    def __init__(self,noOfInputs,threshold=10,learningRate=1):
        self.threshold = threshold
        self.learningRate = learningRate
        self.weights = np.zeros(noOfInputs + 1)
        
    def predict(self,inputs):
        summation = np.dot(inputs,self.weights[1:]) + self.weights[0]
        if summation>0:
            activation = 1
        else:
            activation = 0
        return activation
    
    def train(self,trainingInputs,labels):
        for _ in range(self.threshold):
            for inputs , label in zip(trainingInputs,labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learningRate * (label - prediction) * inputs 
                self.weights[0:] += self.learningRate * (label - prediction)
                print(self.weights)

In [19]:
trainingInputs = []
trainingInputs.append(np.array([1,1]))
trainingInputs.append(np.array([1,0]))
trainingInputs.append(np.array([0,1]))
trainingInputs.append(np.array([0,0]))

    
labels = np.array([1,0,0,0])

perceptron = Perceptron(2)
perceptron.train(trainingInputs,labels)

[1. 2. 2.]
[0. 0. 1.]
[-1. -1. -1.]
[-1. -1. -1.]
[0. 1. 1.]
[-1. -1.  0.]
[-1. -1.  0.]
[-1. -1.  0.]
[0. 1. 2.]
[-1. -1.  1.]
[-1. -1.  1.]
[-1. -1.  1.]
[0. 1. 3.]
[-1. -1.  2.]
[-2. -2.  0.]
[-2. -2.  0.]
[-1.  0.  2.]
[-1.  0.  2.]
[-2. -1.  0.]
[-2. -1.  0.]
[-1.  1.  2.]
[-1.  1.  2.]
[-2.  0.  0.]
[-2.  0.  0.]
[-1.  2.  2.]
[-2.  0.  1.]
[-2.  0.  1.]
[-2.  0.  1.]
[-1.  2.  3.]
[-2.  0.  2.]
[-2.  0.  2.]
[-2.  0.  2.]
[-1.  2.  4.]
[-2.  0.  3.]
[-3. -1.  1.]
[-3. -1.  1.]
[-2.  1.  3.]
[-2.  1.  3.]
[-3.  0.  1.]
[-3.  0.  1.]


In [21]:
inputs = np.array([0,0])
print(perceptron.predict(inputs))

0
